apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ITEM_ORDER_DB_URL
              value: {{ .Values.itemOrderDb.url }}
            - name: ITEM_ORDER_DB_USER
              value: {{ .Values.itemOrderDb.user }}
            - name: ITEM_ORDER_DB_PASSWORD
              value: {{ .Values.itemOrderDb.password }}
