apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
data:
  {{- $files := .Files }}
  {{- range tuple "01-schema.sql" "02-data.sql" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{- end }}