apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-postgres
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}-postgres
  ports:
    - name: postgres
      port: {{ .Values.port }}
      targetPort: postgres