apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-wiremock
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}-wiremock
  ports:
  - name: http
    port: 8080
    targetPort: 8080