[package]
name = "rust-my-playground-github-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
async-trait = "0"

[dev-dependencies]
mockall = "0"