[package]
name = "rust-my-playground-github-cli-e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
cucumber = "0"
tokio = { version = "1", features = ["full"] }

[[test]]
name = "github_cli"
harness = false