[package]
name = "rust-my-playground-github-cli-e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
cucumber = "*"
tokio = { version = "*", features = ["full"] }
reqwest = "*"

[[test]]
name = "github_cli"
harness = false