apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: item-order-postgres
build:
  artifacts:
    - image: booookstore/playground/item-order-postgres
  local:
    push: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: item-order-postgres
        chartPath: helm
        setValues:
          name: item-order-postgres
          postgres_password: password
          port: 8081
        setValueTemplates:
          image: "{{ .IMAGE_FULLY_QUALIFIED_booookstore_playground_item_order_postgres }}"