apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-my-playground-flow-control
data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name }}
  releaseName: {{ $relname }}
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
    - {{ $index }}: {{ $topping }}
    {{- end }}
