#file: noinspection KubernetesUnknownResourcesInspection
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: item-order-api-deps
requires:
  - path: ../item-order-postgres
deploy:
  helm:
    releases:
      - name: item-shop-api
        chartPath: ../wiremock/helm
        setValues:
          name: item-shop-api
          wiremock_image_tag: 2.35.0-1
          port: 8082
          namespace: item-order-service
      - name: item-item-api
        chartPath: ../wiremock/helm
        setValues:
          name: item-item-api
          wiremock_image_tag: 2.35.0-1
          port: 8083
          namespace: item-order-service