#file: noinspection KubernetesUnknownResourcesInspection
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: item-order-api
build:
  artifacts:
    - image: booookstore/playground/item-order-api
      context: ../../../apps/item-order-api
      jib:
        type: maven
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST
      timezone: "Local"
  local:
    useBuildkit: true
    push: false
deploy:
  helm:
    releases:
    - name: item-order-api
      chartPath: helm
      setValues:
        name: item-order-api
      setValueTemplates:
        image: "{{ .IMAGE_FULLY_QUALIFIED_booookstore_playground_item_order_api }}"
    - name: item-search-api
      chartPath: ../wiremock/helm
      setValues:
        name: item-search-api
        wiremock_image_tag: 2.35.0-1
        port: 8081
    - name: item-spec-api
      chartPath: ../wiremock/helm
      setValues:
        name: item-spec-api
        wiremock_image_tag: 2.35.0-1
        port: 8082